
package paquete.view;

import com.mongodb.DB;
import com.mongodb.DBCollection;
import com.mongodb.Mongo;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import paquete.bo.EmpleadoBO;
import paquete.bo.ProductoBO;
import paquete.entity.Empleado;
import paquete.entity.Producto;

public class FormProducto extends javax.swing.JFrame {

    /**
     * Creates new form FormProducto
     */
    private ProductoBO pbo = new ProductoBO();
    private EmpleadoBO ebo = new EmpleadoBO();
    DB db;
    DBCollection tabla;
    
    public FormProducto() {
        try {
            Mongo mongo = new Mongo("LocalHost", 27017);
            db = mongo.getDB("gestion");
            tabla = db.getCollection("pedidos");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se ha podido conectar MongoDB - " + e.getMessage());
        }
        initComponents();
        mostrarProducto();
        mostrarEmpleado();
        idMax();
    }
    public void mostrarProducto()
    {
        pbo.mostrarProducto(tbProductos);
        pbo.listarTienda(tbSelectorProductos);
        TableColumn tc = tbSelectorProductos.getColumnModel().getColumn(5);
        tc.setCellEditor(tbSelectorProductos.getDefaultEditor(Boolean.class));
        tc.setCellRenderer(tbSelectorProductos.getDefaultRenderer(Boolean.class));
        
    }
    
    
    public void mostrarEmpleado()
    {
        ebo.mostrarEmpleado(tbEmpleados);
    }
    
    
    public void idMax()
    {
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        botonModificarProd1 = new javax.swing.JButton();
        botonModificarProd2 = new javax.swing.JButton();
        botonModificarProd3 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        txtDniCliente = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtDniPedido = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        botonModificarProd4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbSelectorProductos = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        botonLimiarEmp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();
        botonSalir1 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        comboCanalVentaEmpleado = new javax.swing.JComboBox<>();
        txtDniEmp = new javax.swing.JTextField();
        txtNombreEmp = new javax.swing.JTextField();
        txtCelularEmp = new javax.swing.JTextField();
        txtCorreoEmp = new javax.swing.JTextField();
        txtBreveteEmp = new javax.swing.JTextField();
        comboPuestoEmpleado = new javax.swing.JComboBox<>();
        botonModificarEmp = new javax.swing.JButton();
        botonEliminarEmp = new javax.swing.JButton();
        botonAgregarEmp = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRegistroSanitario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        botonAgregarprod = new javax.swing.JButton();
        botonModificarProd = new javax.swing.JButton();
        botonEliminarProd = new javax.swing.JButton();
        botonLimipiarProd = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("TOP GUN", 2, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 102));
        jLabel8.setText("Formulario de PEDIDOS");

        botonModificarProd1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarProd1.setText("Desconectar");
        botonModificarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProd1ActionPerformed(evt);
            }
        });

        botonModificarProd2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarProd2.setText("Agregar Producto");
        botonModificarProd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProd2ActionPerformed(evt);
            }
        });

        botonModificarProd3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarProd3.setText("Modificar");
        botonModificarProd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProd3ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("DNI del cliente");

        txtDniCliente.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("DNI del empleado");

        txtDniPedido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(102, 102, 102));
        jLabel28.setText("Información del pedido");

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(102, 102, 102));
        jLabel29.setText("Selección de productos");

        jLabel30.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(102, 102, 102));
        jLabel30.setText("Producto:");

        jLabel31.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(102, 102, 102));
        jLabel31.setText("Cant:");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        botonModificarProd4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarProd4.setText("Añadir");
        botonModificarProd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProd4ActionPerformed(evt);
            }
        });

        tbSelectorProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(tbSelectorProductos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonModificarProd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonModificarProd3)
                        .addGap(18, 18, 18)
                        .addComponent(botonModificarProd4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel27)
                                            .addGap(59, 59, 59)
                                            .addComponent(txtDniPedido))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel26)
                                            .addGap(80, 80, 80)
                                            .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel30)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonModificarProd2)
                .addGap(193, 193, 193))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtDniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(jLabel31)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonModificarProd2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(txtDniPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonModificarProd1)
                    .addComponent(botonModificarProd3)
                    .addComponent(botonModificarProd4))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Pedidos", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Celular");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Correo");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Canal de venta");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel14.setText("Para modificar o eliminar, indique el DNI en el casillero");

        botonLimiarEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonLimiarEmp.setText("LImpiar");
        botonLimiarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimiarEmpActionPerformed(evt);
            }
        });

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbEmpleados);

        botonSalir1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonSalir1.setText("Salir");
        botonSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalir1ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("TOP GUN", 2, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 102));
        jLabel15.setText("Formulario de Empleados");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("DNI");

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Brevete");

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Puesto");

        comboCanalVentaEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIENDA FISICA", "ONLINE", " " }));

        comboPuestoEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VENDEDOR", "GERENTE", "SUPERVISOR", " ", " " }));

        botonModificarEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarEmp.setText("Modificar");
        botonModificarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarEmpActionPerformed(evt);
            }
        });

        botonEliminarEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonEliminarEmp.setText("Eliminar");
        botonEliminarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarEmpActionPerformed(evt);
            }
        });

        botonAgregarEmp.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonAgregarEmp.setText("Agregar");
        botonAgregarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarEmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtCelularEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(comboPuestoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDniEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNombreEmp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                            .addComponent(txtCorreoEmp, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(comboCanalVentaEmpleado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txtBreveteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(botonLimiarEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonModificarEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEliminarEmp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonAgregarEmp)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 459, Short.MAX_VALUE)
                        .addComponent(botonSalir1)
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtDniEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtCelularEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCorreoEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtBreveteEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(comboCanalVentaEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(comboPuestoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonEliminarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(botonAgregarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonModificarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonLimiarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empledos", jPanel3);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("TOP GUN", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Formulario de Productos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Código de producto");

        txtCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Nombre o título");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Reg. Sanitario");

        txtRegistroSanitario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("Stock base (Unidades)");

        txtStock.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("Precio Unitario (S/)");

        txtPrecio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        botonAgregarprod.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonAgregarprod.setText("Agregar");
        botonAgregarprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarprodActionPerformed(evt);
            }
        });

        botonModificarProd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonModificarProd.setText("Modificar");
        botonModificarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarProdActionPerformed(evt);
            }
        });

        botonEliminarProd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonEliminarProd.setText("Eliminar");
        botonEliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarProdActionPerformed(evt);
            }
        });

        botonLimipiarProd.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonLimipiarProd.setText("LImpiar");
        botonLimipiarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimipiarProdActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        jLabel7.setText("Solo para modificar o eliminar:");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));

        tbProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbProductos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtRegistroSanitario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonLimipiarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonModificarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonEliminarProd)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonAgregarprod))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(22, 22, 22)
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel7))
                                .addGap(15, 15, 15)))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtRegistroSanitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonEliminarProd)
                            .addComponent(botonAgregarprod)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(botonModificarProd)
                                .addComponent(botonLimipiarProd)))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Productos", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonLimipiarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimipiarProdActionPerformed
        // TODO add your handling code here:
        limpiarCamposProducto();
    }//GEN-LAST:event_botonLimipiarProdActionPerformed

    private void botonAgregarprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarprodActionPerformed
        // TODO add your handling code here:
        if(txtPrecio.getText().isEmpty() | txtRegistroSanitario.getText().isEmpty()| txtStock.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";
            try {
                int precio = Integer.parseInt(txtPrecio.getText());
                int stock = Integer.parseInt(txtStock.getText());
                int registro = Integer.parseInt(txtRegistroSanitario.getText());
                if(precio + stock + registro >=0) datosCorrectos = true;
                System.out.println("CORRECTO");
                    
            } catch (Exception e) {
                mensajeX = e.getMessage();
                // JOptionPane.showMessageDialog(null, e.getMessage()); 
            }
            if(datosCorrectos)
            {
                int codigo = 0;
                if(txtCodigo.getText()== "")
                {
                    codigo = Integer.parseInt(txtCodigo.getText());
                }
                Producto prod = new Producto();
                prod.setCodProducto(codigo);
                prod.setNombre(txtNombre.getText().toUpperCase());
                prod.setStock(Integer.parseInt(txtStock.getText()));
                prod.setPrecioUnitario(Double.parseDouble(txtPrecio.getText()));
                prod.setRegistroSanitario(Integer.parseInt(txtRegistroSanitario.getText()));
                String mensaje = pbo.agregarProducto(prod);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCamposProducto();
                mostrarProducto();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Algo ha salido mal - " + mensajeX);
            }
            
        }
    }//GEN-LAST:event_botonAgregarprodActionPerformed

    private void botonModificarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProdActionPerformed
        // TODO add your handling code here:
        if(txtPrecio.getText().isEmpty() | txtRegistroSanitario.getText().isEmpty()| txtStock.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";
            try {
                int precio = Integer.parseInt(txtPrecio.getText());
                int stock = Integer.parseInt(txtStock.getText());
                int registro = Integer.parseInt(txtRegistroSanitario.getText());
                if(precio + stock + registro >=0) datosCorrectos = true;
                System.out.println("CORRECTO");
                    
            } catch (Exception e) {
                mensajeX = e.getMessage();
                // JOptionPane.showMessageDialog(null, e.getMessage()); 
            }
            if(datosCorrectos)
            {
                int codigo = 0;
                if(txtCodigo.getText()!= "")
                {
                    codigo = Integer.parseInt(txtCodigo.getText());
                }
                Producto prod = new Producto();
                prod.setCodProducto(codigo);
                prod.setNombre(txtNombre.getText().toUpperCase());
                prod.setPrecioUnitario(Double.parseDouble(txtPrecio.getText()));
                prod.setRegistroSanitario(Integer.parseInt(txtRegistroSanitario.getText()));
                String mensaje = pbo.modificarProducto(prod);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCamposProducto();
                mostrarProducto();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error en el código - " + mensajeX);
            }
        }
    }//GEN-LAST:event_botonModificarProdActionPerformed

    private void botonEliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarProdActionPerformed
        // TODO add your handling code here:
        if(txtCodigo.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese el código");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";

            try {
                int codigo = Integer.parseInt(txtCodigo.getText());
                datosCorrectos = true;
                    
            } catch (Exception e) {
                mensajeX = e.getMessage();
            }
            if(datosCorrectos)
            {
                int codigo = 0;
                if(txtCodigo.getText()!= "")
                {
                    codigo = Integer.parseInt(txtCodigo.getText());
                }
                String mensaje = pbo.eliminarProducto(codigo);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCamposProducto();
                mostrarProducto();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error en el código - " + mensajeX);
            }
        }
    }//GEN-LAST:event_botonEliminarProdActionPerformed

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void botonSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalir1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalir1ActionPerformed

    private void botonLimiarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimiarEmpActionPerformed
        // TODO add your handling code here:
        limpiarCamposEmpleado();
    }//GEN-LAST:event_botonLimiarEmpActionPerformed

    private void botonModificarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarEmpActionPerformed
        // TODO add your handling code here:
        String canal = "";
        String puesto = "";
        Empleado emp = new Empleado();
        canal = comboCanalVentaEmpleado.getSelectedItem().toString();
        puesto = comboPuestoEmpleado.getSelectedItem().toString();
        
        if(txtBreveteEmp.getText().isEmpty()|txtCorreoEmp.getText().isEmpty()| txtNombreEmp.getText().isEmpty() | txtCelularEmp.getText().isEmpty() | txtDniEmp.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos a modificar");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";
            try {
                int dni = Integer.parseInt(txtDniEmp.getText());
                int celular = Integer.parseInt(txtCelularEmp.getText());
                int brevete = Integer.parseInt(txtBreveteEmp.getText());
                if(dni + celular +brevete >=0) datosCorrectos = true;
                System.out.println("CORRECTO");
                
            } catch (Exception e) {
                mensajeX = e.getMessage();
            }
            int dni = 0;
            if(txtDniEmp.getText()!="")
            {
                dni = Integer.parseInt(txtDniEmp.getText());
                System.out.println("-----------------------DNI: " + dni);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "No se ha proporcionado un dni correcto");
            }
            
            emp.setDni(dni);
            System.out.println("-----------------------DNI: " + emp.getDni());
            emp.setNombre(txtNombreEmp.getText());
            emp.setCelular(Integer.parseInt(txtCelularEmp.getText()));
            emp.setCorreo(txtCorreoEmp.getText());
            emp.setBrevete(Integer.parseInt(txtBreveteEmp.getText()));
            emp.setCanalVenta(canal);
            emp.setPuesto(puesto);
            String mensaje = ebo.modificarEmpleado(emp);
            JOptionPane.showMessageDialog(null, mensaje);
            // limpiarCamposEmpleado();
            mostrarEmpleado();
        }
    }//GEN-LAST:event_botonModificarEmpActionPerformed

    private void botonEliminarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarEmpActionPerformed
        // TODO add your handling code here:
        if(txtDniEmp.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Ingrese un DNI válido");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";
            try {
                int dni = Integer.parseInt(txtDniEmp.getText());
                datosCorrectos = true;
            } catch (Exception e) {
                mensajeX = e.getMessage();
            }
            if(datosCorrectos)
            {
                int dni = 0;
                if(txtDniEmp.getText()!="")
                {
                    dni = Integer.parseInt(txtDniEmp.getText());
                }
                String mensaje = ebo.eliminarEmpleado(dni);
                JOptionPane.showMessageDialog(null, mensaje);
                mostrarEmpleado();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Error en el DNI - " + mensajeX);
            }
                    
        }
    }//GEN-LAST:event_botonEliminarEmpActionPerformed

    private void botonAgregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarEmpActionPerformed
        // TODO add your handling code here:
        String canal = "";
        String puesto = "";
        canal = comboCanalVentaEmpleado.getSelectedItem().toString();
        puesto = comboPuestoEmpleado.getSelectedItem().toString();
        
        
        if(txtDniEmp.getText().isEmpty() | txtNombreEmp.getText().isEmpty() |txtCelularEmp.getText().isEmpty()|
                txtCorreoEmp.getText().isEmpty() | txtBreveteEmp.getText().isEmpty() | canal == "" | puesto == "")
        {
            JOptionPane.showMessageDialog(null, "Inserte toda la información necesaria");
        }
        else
        {
            boolean datosCorrectos = false;
            String mensajeX = "";
            try {
                int dni = Integer.parseInt(txtDniEmp.getText());
                int celular = Integer.parseInt(txtCelularEmp.getText());
                int brevete = Integer.parseInt(txtBreveteEmp.getText());
                if(dni + celular +brevete >=0) datosCorrectos = true;
                System.out.println("CORRECTO");
                    
            } catch (Exception e) {
                mensajeX = e.getMessage();
            }
            if(datosCorrectos)
            {
                int dni = 0;
                if(txtDniEmp.getText()!="")
                {
                    dni = Integer.parseInt(txtDniEmp.getText());
                }
                else
                {
                    JOptionPane.showMessageDialog(null, "No se ha proporcionado un dni correcto");
                }
                System.out.println("DNI: "+dni);
                Empleado emp = new Empleado();
                emp.setDni(dni);
                emp.setNombre(txtNombreEmp.getText().toUpperCase());
                emp.setCelular(Integer.parseInt(txtCelularEmp.getText()));
                emp.setCorreo(txtCorreoEmp.getText().toUpperCase());
                emp.setBrevete(Integer.parseInt(txtBreveteEmp.getText()));
                emp.setCanalVenta(canal);
                emp.setPuesto(puesto);
                String mensaje = ebo.agregarEmpleado(emp);
                JOptionPane.showMessageDialog(null, mensaje);
                limpiarCamposEmpleado();
                mostrarEmpleado();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Algo ha salido mal - " + mensajeX);
            }
            
        }
        
    }//GEN-LAST:event_botonAgregarEmpActionPerformed

    private void botonModificarProd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProd3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarProd3ActionPerformed

    private void botonModificarProd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProd2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Producto agregado correctamente");
    }//GEN-LAST:event_botonModificarProd2ActionPerformed

    private void botonModificarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProd1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonModificarProd1ActionPerformed

    private void botonModificarProd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarProd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarProd4ActionPerformed

    public void limpiarCamposProducto()
    {
        txtCodigo.setText("");
        txtNombre.setText("");
        txtPrecio.setText("");
        txtRegistroSanitario.setText("");
        txtStock.setText("");
    }
    
    public void limpiarCamposEmpleado()
    {
        txtDniEmp.setText("");
        txtNombreEmp.setText("");
        txtCelularEmp.setText("");
        txtCorreoEmp.setText("");
        txtBreveteEmp.setText("");
    }
    
    public boolean isSelected(int fila, int columna, JTable table)
    {
        return table.getValueAt(fila,columna) !=null;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAgregarEmp;
    private javax.swing.JButton botonAgregarprod;
    private javax.swing.JButton botonEliminarEmp;
    private javax.swing.JButton botonEliminarProd;
    private javax.swing.JButton botonLimiarEmp;
    private javax.swing.JButton botonLimipiarProd;
    private javax.swing.JButton botonModificarEmp;
    private javax.swing.JButton botonModificarProd;
    private javax.swing.JButton botonModificarProd1;
    private javax.swing.JButton botonModificarProd2;
    private javax.swing.JButton botonModificarProd3;
    private javax.swing.JButton botonModificarProd4;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonSalir1;
    private javax.swing.JComboBox<String> comboCanalVentaEmpleado;
    private javax.swing.JComboBox<String> comboPuestoEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable tbEmpleados;
    private javax.swing.JTable tbProductos;
    private javax.swing.JTable tbSelectorProductos;
    private javax.swing.JTextField txtBreveteEmp;
    private javax.swing.JTextField txtCelularEmp;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtCorreoEmp;
    private javax.swing.JTextField txtDniCliente;
    private javax.swing.JTextField txtDniEmp;
    private javax.swing.JTextField txtDniPedido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreEmp;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtRegistroSanitario;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
